package com.example.solomon.feature.chat.application.in.usecase;

import com.datastax.oss.driver.api.core.CqlSession;
import com.datastax.oss.driver.api.core.cql.Row;
import com.example.solomon.KafkaTestSupport;
import com.example.solomon.SlicedSpringContextTest;
import com.example.solomon.TestContainersConfig;
import com.example.solomon.common.adapter.out.persistence.cache.redis.config.RedisPropertiesConfig;
import com.example.solomon.common.adapter.out.persistence.cache.redis.config.TrialCacheRedisConfig;
import com.example.solomon.feature.chat.adapter.out.persistence.ChatMessageRepositoryAdapter;
import com.example.solomon.feature.chat.adapter.out.persistence.cache.redis.RedisChatMessageSeqRepository;
import com.example.solomon.feature.chat.application.in.usecase.dto.CreateChatMessageCommand;
import com.example.solomon.feature.chat.domain.entity.MessageType;
import com.github.f4b6a3.uuid.UuidCreator;
import org.awaitility.Awaitility;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.data.cassandra.DataCassandraTest;
import org.springframework.context.annotation.Import;
import org.springframework.test.context.ActiveProfiles;

import java.time.Duration;
import java.util.List;

import static com.example.solomon.feature.chat.adapter.in.messaging.kafka.config.ChatKafkaTopicConfig.CDC_SCYLLA_CHAT_MESSAGE;
import static org.assertj.core.api.Assertions.assertThat;

@ActiveProfiles("test")
@SlicedSpringContextTest
@Import({
        TestContainersConfig.class,
        CreateChatMessageUsecase.class,
        ChatMessageRepositoryAdapter.class,
        RedisChatMessageSeqRepository.class,
        RedisPropertiesConfig.class,
        TrialCacheRedisConfig.class
})
@DataCassandraTest
class CreateChatMessageUsecaseTest {

    @Autowired
    private KafkaTestSupport kafkaTestSupport;

    @Autowired
    private CreateChatMessageUsecase createChatMessageUsecase;


    @Autowired
    private CqlSession cqlSession;

    @Test
    void testCreateChatMessageUsecase() throws InterruptedException {
        // Given
        CreateChatMessageCommand command = new CreateChatMessageCommand(UuidCreator.getTimeOrderedEpoch(), 1L, "test", MessageType.USER);

        // When
        createChatMessageUsecase.execute(command);

        // Then
        String tableName = "localscylla.chat_message_scylla_cdc_log"; // ScyllaDB does not support outbox pattern.
        // the changes are written on the cdc table automatically generated by ScyllaDB.

        Awaitility.await()
                .atMost(Duration.ofSeconds(10))
                .untilAsserted(() -> {
                    List<Row> rows = cqlSession.execute("""
                            SELECT *
                            FROM %s
                            """.formatted(tableName)).all();

                    assertThat(rows).isNotEmpty();
                });

        assertThat(kafkaTestSupport.pollRecords(CDC_SCYLLA_CHAT_MESSAGE)).isNotEmpty();
    }

}