spring:
  config:
    activate:
      on-profile: local
    import:
      - optional:classpath:/config/local/application-local-kafka.yml
      - optional:classpath:/config/local/application-local-mysql.yml
      - optional:classpath:/config/local/application-local-redis.yml
      - optional:classpath:/config/local/application-local-oauth2.yml
      - optional:file:./env/local.env[.properties]

logging:
  level:
    com.example.solomon.common.adapter.in.web.security.handler: debug