services:
  # ========================
  # MySQL
  # ========================
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: localdb
      MYSQL_USER: localuser
      MYSQL_PASSWORD: localpass
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-time-zone=+09:00
      - --server-id=1
      - --log-bin=mysql-bin
      - --binlog-format=ROW
      - --binlog-row-image=FULL
      - --binlog-expire-logs-seconds=604800
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-prootpass"]
      interval: 5s
      timeout: 3s
      retries: 30
    volumes:
      - mysql-data:/var/lib/mysql
      - ./dbz.sql:/docker-entrypoint-initdb.d/dbz.sql

  # ========================
  # Scylla
  # ========================
  scylla:
    image: scylladb/scylla:2026.1.7
    ports:
      - "9042:9042"
    command: --smp 1 --memory 2G
    healthcheck:
      test: ["CMD-SHELL", "nodetool status | grep -E '^UN' || exit 1"]
      interval: 5s 
      timeout: 3s 
      retries: 30    
    volumes:
          - scylla_data:/var/lib/scylla
  
  scylla-init:
    image: scylladb/scylla:2026.1.7
    depends_on:
      scylla:
        condition: service_healthy
    volumes:
      - ./init.cql:/init.cql:ro
    entrypoint:
      - /bin/sh
      - -c
      - |
        echo "Initializing Scylla..."
        cqlsh scylla 9042 -f /init.cql
        echo "Done."

  # ========================
  # Kafka
  # ========================
  kafka:
    image: confluentinc/cp-kafka:8.2.2
    ports:
      - "9092:9092"
    environment:
      CLUSTER_ID: "ciWo7IWazngRchmPES6q5A=="
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:19093"
      KAFKA_LISTENERS: "INTERNAL://kafka:19092,CONTROLLER://kafka:19093,EXTERNAL://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:19092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server kafka:19092"]
      interval: 5s
      timeout: 3s
      retries: 30
    volumes:
      - kafka-data:/var/lib/kafka/data

  # ========================
  # Kafka Connect
  # ========================
  kafka-connect:
    build:
          context: .
          dockerfile: debezium-image.Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      kafka:
        condition: service_healthy
      mysql:
        condition: service_healthy
      scylla-init:
        condition: service_completed_successfully
    environment:
      BOOTSTRAP_SERVERS: kafka:19092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect-configs
      OFFSET_STORAGE_TOPIC: connect-offsets
      STATUS_STORAGE_TOPIC: connect-status
      CONFIG_STORAGE_REPLICATION_FACTOR: 1
      OFFSET_STORAGE_REPLICATION_FACTOR: 1
      STATUS_STORAGE_REPLICATION_FACTOR: 1
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
      CONNECT_TOPIC_CREATION_ENABLE: "true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/"]
      interval: 5s
      timeout: 3s
      retries: 30

  # ========================
  # MySQL Connector Bootstrap
  # ========================
  connect-bootstrap:
    image: curlimages/curl:8.5.0
    depends_on:
      kafka-connect:
        condition: service_healthy
    volumes:
      - ./mysql-connector-config.json:/mysql-connector-config.json
    entrypoint:
      - sh
      - -c
      - |
        echo "registering...."

        curl -X POST http://kafka-connect:8083/connectors \
          -H "Content-Type: application/json" \
          -d @/mysql-connector-config.json

        echo "done"

  # ========================
  # Scylla Connector Bootstrap
  # ========================
  scylla-connect-bootstrap:
    image: curlimages/curl:8.5.0
    depends_on:
      kafka-connect:
        condition: service_healthy
    volumes:
      - ./scylla-connector-config.json:/scylla-connector-config.json
    entrypoint:
      - sh
      - -c
      - |
        echo "registering...."

        curl -X POST http://kafka-connect:8083/connectors \
          -H "Content-Type: application/json" \
          -d @/scylla-connector-config.json

        echo "done"
        
  # ========================
  # Kafka UI
  # ========================
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - "8084:8080"
    depends_on:
      - kafka
      - kafka-connect
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:19092
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: debezium
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://kafka-connect:8083

volumes:
  mysql-data:
  scylla_data:
  kafka-data: