spring:
  datasource:
    url: jdbc:mysql://localhost:3306/localmysql?serverTimezone=UTC&characterEncoding=UTF-8
    username: localuser
    password: localpass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE